
// Finally,
#include <catch2/catch.hpp>

//////////////////////////////////////////////////////////////////////

TEST_CASE("Return exit code", "[vm]") {
}

//////////////////////////////////////////////////////////////////////
